- name: Install DSE packages (yum)
  yum:
    name: item
    update_cache: yes
    state: installed
  with_items:
    - dse-full
    - datastax-agent
  when: ansible_os_family == "RedHat"

- name: Install DSE packages (apt)
  apt:
    name: item
    update_cache: yes
    state: installed
  with_items:
    - dse-full
    - datastax-agent
  when: ansible_os_family == "Debian"

- name: Reload systemd
  sudo: yes
  command: systemctl daemon-reload
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- include: config.yml
  tags:
    - configuration

- meta: flush_handlers

- name: Start DSE service
  service: name=dse state=started enabled=yes
  tags:
    - services

- name: Start DataStax Agent
  service: name=datastax-agent state=started enabled=yes
  tags:
    - services
