---
- name: move external interface to proper zone
  command: firewall-cmd --zone=external --change-interface='{{ external_int }}'
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: move internal interface to proper zone
  command: firewall-cmd --zone=internal --change-interface='{{ internal_int  }}'
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: setup firewalld external allows
  command: firewall-cmd --permanent --zone=external --add-rich-rule='rule family="ipv4" source address="{{ hostvars[item][['ansible_', hostvars[item]['cluster_interface']]|join]['ipv4']['address'] }}" accept'
  with_items: play_hosts
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: setup firewalld internal allows
  command: firewall-cmd --permanent --zone=internal --add-rich-rule='rule family="ipv4" source address="{{ hostvars[item][['ansible_', hostvars[item]['cluster_interface']]|join]['ipv4']['address'] }}" accept'
  with_items: play_hosts
  notify: reload firewalld
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Set UFW rules between cluster nodes
  ufw: rule=allow src={{ hostvars[item][['ansible_', hostvars[item]['cluster_interface']]|join]['ipv4']['address'] }}
  with_items: play_hosts
  when: ansible_distribution == "Ubuntu"
