---
- name: move external interface to proper zone
  command: firewall-cmd --zone=external --change-interface='{{ external_int }}'

- name: move internal interface to proper zone
  command: firewall-cmd --zone=internal --change-interface='{{ internal_int  }}'

- name: setup firewalld external allows 
  command: firewall-cmd --permanent --zone=external --add-source='{{ hostvars[item]['ansible_eth0']['ipv4']['address'] }}/32' 
  with_items: play_hosts

- name: setup firewalld internal allows 
  command: firewall-cmd --permanent --zone=internal --add-source='{{ hostvars[item]['ansible_eth1']['ipv4']['address'] }}/32'
  with_items: play_hosts
  notify: reload firewalld



#- name: setup firewalld external allows 
#  firewalld: source='{{ hostvars[item]['ansible_eth0']['ipv4']['address'] }}/32' perminent=true state=enabled
#  with_items: play_hosts
#
#- name: setup firewalld internal allows 
#  firewalld: source='{{ hostvars[item]['ansible_eth1']['ipv4']['address'] }}/32' perminent=true state=enabled
#  with_items: play_hosts
