---
- name: Set swappiness to 1
  sysctl: name=vm.swappiness value=0 state=present

- include: firewalld.yml
  tags:
    - firewall

- name: install java
  yum: name=java-1.7.0-openjdk state=installed

- name: Upload Datastax Repo
  template: src=datastax_repo.j2 dest=/etc/yum.repos.d/datastax.repo mode=0644

- name: install DSE 
  yum: name=dse-full state=installed

- include: config.yml

- name: start dse service
  service: name=dse state=started

- name: install dse agent
  yum: name=datastax-agent state=installed

- name: start dse agent
  service: name=datastax-agent state=started


