---
- name: Set swappiness to 1
  sysctl: name=vm.swappiness value=0 state=present
  tags:
    - configuration

- include: firewalld.yml
  tags:
    - firewall

- name: Setup hosts file
  template: src=hosts.j2 dest=/etc/hosts mode=0644

- name: Install epel
  yum: name="https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm" state=present update_cache=yes
  when: ansible_os_family == "RedHat"

- name: install required packages
  yum: name={{ item }} state=installed
  with_items:
    - java-1.8.0-openjdk-devel
    - python-httplib2
    - sysstat
    - lsof
    - parted
    - openssh-clients
    - unzip
    - curl
    - wget
    - iotop
    - ntpdate
    - chrony
    - nmap-ncat
  tags:
    - packages

- name: Start the NTP service
  service: name=chronyd state=started enabled=yes
  tags:
    - services

- name: Set the tuned profile
  copy: src=tuned.conf
        dest=/etc/tuned/hadoop/
        mode=0755
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Activate the tuned profile
  shell: tuned-adm profile hadoop
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Upload Datastax Repo
  template: src=datastax_repo.j2 dest=/etc/yum.repos.d/datastax.repo mode=0644
  tags:
    - packages
