---
- name: Set swappiness to 1
  sysctl: name=vm.swappiness value=0 state=present
  tags:
    - configuration

- include: firewalld.yml
  tags:
    - firewall

- name: Setup hosts file
  template: src=hosts.j2 dest=/etc/hosts mode=0644

- name: install required packages
  yum: name={{ item }} state=installed
  with_items:
    - epel-release
    - java-1.8.0-openjdk
    - python-httplib2
    - ntp
  tags:
    - packages

- name: start ntpd
  service: name=ntpd state=started
  tags:
    - services

- name: Upload Datastax Repo
  template: src=datastax_repo.j2 dest=/etc/yum.repos.d/datastax.repo mode=0644
  tags:
    - packages

- name: install DSE 
  yum: name=dse-full state=installed
  tags:
    - packages

- include: config.yml
  tags:
    - configuration

- name: start dse service
  service: name=dse state=started
  tags:
    - services

- name: install dse agent
  yum: name=datastax-agent state=installed
  tags:
    - packages

- name: start dse agent
  service: name=datastax-agent state=started
  tags:
    - services
