---
- name: Set swappiness to 1
  sysctl: name=vm.swappiness value=0 state=present
  tags:
    - configuration

- include: firewalld.yml
  tags:
    - firewall

- name: Setup hosts file
  template: src=hosts.j2 dest=/etc/hosts mode=0644

- name: install required packages
  yum: name={{ item }} state=installed
  with_items:
    - epel-release
    - java-1.8.0-openjdk-devel
    - python-httplib2
    - sysstat
    - lsof
    - parted
    - openssh-clients
    - unzip
    - curl
    - wget
    - iotop
    - ntpdate
    - chrony
    - nmap-ncat
  tags:
    - packages

- name: Start the NTP service
  service: name=chronyd state=started enabled=yes
  tags:
    - services

- name: Upload Datastax Repo
  template: src=datastax_repo.j2 dest=/etc/yum.repos.d/datastax.repo mode=0644
  tags:
    - packages
