packages:
    - openjdk-7-jdk
    - python-simplejson
    - python-httplib2
    - man-db
    - vim
    - sysstat
    - lsof
    - netcat
    - ntp
    - parted
    - iotop
    - unzip
    - curl
    - wget
    - ifenslave

update_grub: "/usr/sbin/update-grub"

ntp_service: ntp
ntp_sync: "/usr/sbin/ntpd -gq"

resolv_conf: "/etc/resolvconf/resolv.conf.d/tail"

networking_path: "/etc/network/interfaces.d"
networking_eth: "debian-ifcfg-eth.j2"
networking_bond: "debian-ifcfg-bond.j2"

datastax_repo: "debian-datastax_repo.j2"
datastax_repo_file: "/etc/apt/sources.list.d/datastax.sources.list"
