---
- name: reload firewalld
  command: firewall-cmd --reload
  notify: Gather facts

- name: Gather facts
  action: setup

- name: update-grub
  shell: "{{ update_grub }}"
  when: "{{ ansible_distribution_major_version|int }} > 6"
