---
- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: restart dse
  service: name=dse state=restarted
  notify: sleep

- name: restart datastax agent
  service: name=datastax-agent state=restarted

- name: Gather facts
  action: setup

- name: sleep
  pause: seconds=30
