---
- name: Install OpsCenter (yum)
  yum:
    name: item
    update_cache: yes
    state: installed
  with_items:
    - opscenter
  when: ansible_os_family == "RedHat"

- name: Install OpsCenter (apt)
  apt:
    name: item
    update_cache: yes
    state: installed
  with_items:
    - opscenter
  when: ansible_os_family == "Debian"

- name: start opscenter
  service: name=opscenterd state=started
  notify: sleep

- meta: flush_handlers

- name: upload cluster definition
  template: src=cluster_def.j2 dest=/tmp/cluster_def mode=0644
  tags:
    - cluster_create

- name: Slurp the cluster definition
  slurp: src=/tmp/cluster_def
  register: cluster_def
  tags:
    - cluster_create

- name: Check if cluster config already exists
  uri:
    url=http://{{ ansible_fqdn }}:8888/cluster-configs/{{ cluster_name }}
    method=GET
    status_code=200,201,202,404
    return_content=yes
  register: current_config
  tags:
    - cluster_create

- name: register cluster in opscenter
  uri:
    url=http://{{ ansible_fqdn }}:8888/cluster-configs
    method=POST
    body='{{ cluster_def.content | b64decode }}'
    body_format=json
    timeout=120
    status_code=201
  when: current_config.status==404
  register: cluster
  tags:
    - cluster_create

- name: Update cluster config in opscenter
  uri:
    url=http://{{ ansible_fqdn }}:8888/cluster-configs/{{ cluster_name }}
    method=PUT
    body='{{ cluster_def.content | b64decode }}'
    body_format=json
    timeout=120
    status_code=204
  when: current_config.status==200
  register: cluster
  tags:
    - cluster_create

#- name: login to opscenter and get session 
#  uri:
#    url: {{ ansible_fqdn }}/opscenter/index.html
#    method: POST
#    user: {{ opscenter_user }}
#    password: {{ opscenter_pass }}
#    force_basic_auth: yes
#    status_code: 201
#  register: sessionid
