---
- name: Load OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../vars

- name: Install OpsCenter
  action: "{{ package_info.pkg_mgr }}"
  args: package_info.args
  tags:
    - packages

- name: start opscenter
  service: name=opscenterd state=started

- name: upload cluster definition
  template: src=cluster_def.j2 dest=/tmp/cluster_def mode=0644
  tags:
    - cluster_create

- name: Slurp the cluster definition
  slurp: src=/tmp/cluster_def
  register: cluster_def
  tags:
    - cluster_create

- name: register cluster in opscenter
  uri:
    url=http://{{ opscenter_uri }}:8888/cluster-configs
    method=POST
    body='{{ cluster_def.content | b64decode }}'
    status_code=201
  register: cluster
  tags:
    - cluster_create
  notify: restart datastax-agent  

#- name: login to opscenter and get session 
#  uri:
#    url: {{ opscenter_uri }}/opscenter/index.html
#    method: POST
#    user: {{ opscenter_user }}
#    password: {{ opscenter_pass }}
#    force_basic_auth: yes
#    status_code: 201
#  register: sessionid
