- set_fact: outer_loop="{{ item }}"

- add_host:
    name: "{{ hostvars[item].inventory_hostname }}"
    ansible_host: "{{ hostvars[item].ansible_host|default(hostvars[item].ansible_ssh_host) }}"
    ansible_user: "{{ hostvars[item].ansible_user|default('root') }}"
    ansible_ssh_pass: "{{ hostvars[item].ansible_ssh_pass|default('') }}"
    ansible_become_user: root
    ansible_become_pass: "{{ hostvars[item].ansible_ssh_pass|default('') }}"
    groups: "dse-cluster"
    dc_name: "{{ outer_loop.dc_name }}"
    options: "{{ outer_loop.options }}"
    rack_name: "{{ hostvars[item].rack_name|default('RAC1') }}"
  with_items: "{{ groups[outer_loop.options.group] }}"
  when: "{{ outer_loop.options.group != opscenter_group_name }}"
  tags:
    - always

- add_host:
    name: "{{ hostvars[item].inventory_hostname }}"
    ansible_host: "{{ hostvars[item].ansible_host|default(hostvars[item].ansible_ssh_host) }}"
    ansible_user: "{{ hostvars[item].ansible_user|default('root') }}"
    ansible_ssh_pass: "{{ hostvars[item].ansible_ssh_pass|default('') }}"
    ansible_become_user: root
    ansible_become_pass: "{{ hostvars[item].ansible_ssh_pass|default('') }}"
    groups: "dse-seeds"
    dc_name: "{{ outer_loop.dc_name }}"
    options: "{{ outer_loop.options }}"
    rack_name: "{{ hostvars[item].rack_name|default('RAC1') }}"
  with_items: "{{ groups[outer_loop.options.group]|sort|slice(2)|list|first }}"
  when: "{{ outer_loop.options.group != opscenter_group_name }}"
  tags:
    - always

- add_host:
    name: "{{ hostvars[item].inventory_hostname }}"
    ansible_host: "{{ hostvars[item].ansible_host|default(hostvars[item].ansible_ssh_host) }}"
    ansible_user: "{{ hostvars[item].ansible_user|default('root') }}"
    ansible_ssh_pass: "{{ hostvars[item].ansible_ssh_pass|default('') }}"
    ansible_become_user: root
    ansible_become_pass: "{{ hostvars[item].ansible_ssh_pass|default('') }}"
    groups: "{{ opscenter_group_name }}"
    dc_name: "{{ outer_loop.dc_name }}"
    options: "{{ outer_loop.options }}"
    rack_name: "{{ hostvars[item].rack_name|default('RAC1') }}"
  with_items: "{{ groups[outer_loop.options.group]|sort|list|first }}"
  when: "{{ outer_loop.dc_name == opscenter_dc }}"
  tags:
    - always
