---
- name: "Add nodes to required groups"
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: "Add nodes to dse-cluster and dse-seeds groups"
      include: add_nodes.yml
      when: ((outer_loop is defined and outer_loop.options.group) or item.options.group) and ((outer_loop is defined and groups[outer_loop.options.group]|length > 0) or groups[item.options.group]|length > 0)
      with_items:
        - "{{ topology }}"

- name: "Apply the dse and datastax-agent roles to all nodes"
  hosts: dse-cluster
  any_errors_fatal: true
  sudo: yes
  sudo_user: root
  remote_user: root
  roles:
    - dse
    - datastax-agent

- name: "Apply the opscenter role to the opscenter group"
  hosts: opscenter-node
  any_errors_fatal: true
  remote_user: root
  roles:
    - role: opscenter
      opscenter_config:
        default_api_timeout: 60
        add_cluster_timeout: 120
  tags:
    - opscenter

- name: "Restart the datastax-agent on all nodes"
  hosts: dse-cluster
  any_errors_fatal: true
  sudo: yes
  sudo_user: root
  remote_user: root
  gather_facts: False
  tasks:
    - name: "Restart the datastax-agent service"
      service: name=datastax-agent state=restarted
