- name: "Add nodes to required groups"
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: "Add the first node to the opscenter variable group"
      add_host:
        name: "{{ hostvars[item].inventory_hostname }}"
        groups: opscenter-nodes
      with_items: groups['dse-nodes']|sort|first
      tags:
      - always
    - name: "Add all cluster nodes to the dse-cluster group"
      add_host:
        name: "{{ hostvars[item].inventory_hostname }}"
        groups: dse-cluster
      with_flattened:
        - groups['dse-nodes']|default([])
        - groups['opscenter-nodes']|default([])
      tags:
      - always


- name: "Apply the common role to all nodes"
  hosts: dse-cluster
  remote_user: root
  roles:
    - common

- name: "Apply the dse role to dse nodes"
  hosts: dse-nodes
  remote_user: root
  roles:
    - dse

- name: "Apply the opscenter role to the opscenter nodes"
  hosts: opscenter-nodes
  remote_user: root
  roles:
    - opscenter
  tags:
    - opscenter
