- name: Create the SSH keypair for {{ item.options.cloud.region }} region
  local_action:
    module: rax_keypair
    credentials: "{{ cloud_config.credentials_filename }}"
    name: "{{ cloud_config.ssh.keyname }}"
    public_key: "{{ lookup('file', cloud_config.ssh.keyfile) }}"
    region: "{{ item.options.cloud.region }}"

- name: Create dse nodes for {{ item.dc_name }} dc
  local_action:
    module: rax
    credentials: "{{ cloud_config.credentials_filename }}"
    name: "{{ item.options.group }}-%02d.{{ cloud_config.domain|lower }}"
    image: "{{ item.options.cloud.image }}"
    flavor: "{{ item.options.cloud.flavor }}"
    region: "{{ item.options.cloud.region }}"
    key_name: "{{ cloud_config.ssh.keyname }}"
    exact_count: yes
    auto_increment: true
    group: "{{ item.options.group }}"
    state: present
    count: "{{ item.options.cloud.nodes_count }}"
    wait: true
    wait_timeout: 900
  register: rax_dse

- name: Build Rackspace CBS for {{ item.dc_name }} dc
  include: provision_cbs.yml
  loop_control:
    loop_var: rax_item
  with_items:
    - "{{ rax_dse.instances }}"
  when: item.options.cbs.build_cbs
