- name: Create CBS Volumes for {{ rax_item.name }}
  local_action:
    module: rax_cbs
    credentials: "{{ credentials_filename }}"
    name: "{{ rax_item.name }}_{{ local_item }}"
    volume_type: "{{ item.options.cbs.disks_type }}"
    size: "{{ item.options.cbs.disks_size }}"
    region: "{{ item.options.cloud.region }}"
    state: present
    wait: true
  loop_control:
    loop_var: local_item
  with_items:
    - "{{ item.options.data_disks_devices }}"

- name: Attach CBS Volumes to {{ rax_item.name }}
  local_action:
    module: rax_cbs_attachments
    credentials: "{{ credentials_filename }}"
    volume: "{{ rax_item.name }}_{{ local_item }}"
    server: "{{ rax_item.id }}"
    region: "{{ item.options.cloud.region }}"
    device: "/dev/{{ local_item }}"
    state: present
    wait: true
  loop_control:
    loop_var: local_item
  with_items:
    - "{{ item.options.data_disks_devices }}"
